# Generated by Django 5.2.15 on 2026-06-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorprofile_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='additional_info',
            field=models.TextField(blank=True, help_text="Write paragraphs normally, and start lines with '*' to create bullet points.", null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='followup_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
