# Generated by Django 5.2.15 on 2026-06-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctorprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='followup_fee',
        ),
        migrations.AlterField(
            model_name='doctorexperience',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank if currently working here', null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='qualification',
            field=models.TextField(blank=True, help_text='E.g., BUMS (Rajshahi Medical University) M.Sc...'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='registration_number',
            field=models.CharField(blank=True, help_text='E.g., U-543', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty_description',
            field=models.TextField(blank=True, help_text='For displaying specialized medical services text'),
        ),
    ]
