# Generated by Django 5.2.15 on 2026-06-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_doctorprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='follow_up_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for follow-up visits', max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='follow_up_validity_days',
            field=models.PositiveIntegerField(default=14, help_text='Number of days the follow-up fee is applicable'),
        ),
    ]
