# Generated by Django 5.2.15 on 2026-06-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctorprofile_follow_up_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_info',
            field=models.TextField(blank=True, help_text='এডমিন নির্দেশিকা: ডক্টরের মূল পরিচিতি, চিকিৎসাপ্রাপ্ত রোগের তালিকা এবং নিচের স্লোগানটি ইমেজের বা প্রেসক্রিপশনের মতো হুবহু এন্টার (New Line) দিয়ে দিয়ে এখানে পেস্ট করুন। কোনো প্রকার HTML ট্যাগ ব্যবহারের প্রয়োজন নেই, ফ্রন্টএন্ডে এটি স্বয়ংক্রিয়ভাবে সাজিয়ে নিবে।', null=True),
        ),
    ]
