# Generated by Django 5.2.15 on 2026-06-18 04:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doctorprofile_doctor_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Upload doctor's profile picture to Cloudinary (Optional)", max_length=255, null=True, verbose_name='image'),
        ),
    ]
