# Generated by Django 5.2.15 on 2026-06-18 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_doctorprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Enter patient's valid phone number", max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01XXXXXXXXX' or '+8801XXXXXXXXX'. Up to 14 digits allowed.", regex='^\\+?(88)?01[3-9]\\d{8}$')]),
        ),
    ]
