# Generated by Django 5.2.15 on 2026-06-18 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_patientprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this doctor is approved by admin.'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this patient is approved by admin.'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='doctor_info',
            field=models.TextField(blank=True, help_text='এডমিন নির্দেশিকা: ডক্টরের মূল পরিচিতি, চিকিৎসাপ্রাপ্ত রোগের তালিকা এবং নিচের স্লোগানটি ইমেজের বা প্রেসক্রিপশনের মতো হুবহু এন্টার (New Line) দিয়ে দিয়ে এখানে পেস্ট করুন। কোনോ প্রকার HTML ট্যাগ ব্যবহারের প্রয়োজন নেই, ফ্রন্টএন্ডে এটি স্বয়ংক্রিয়ভাবে সাজিয়ে নিবে।', null=True),
        ),
    ]
