# Generated by Django 5.2.15 on 2026-06-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_doctorprofile_created_at_doctorprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='doctor_info',
            field=models.TextField(blank=True, help_text="Admin Guideline: Paste the doctor's main introduction, treated disease list, and slogan exactly as it appears on their prescription or image using the Enter key (New Line). No HTML tags are required; the frontend will format it automatically.", null=True),
        ),
    ]
