# Generated by Django 5.2.15 on 2026-07-11 21:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_doctorprofile_doctor_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Upload patient's profile picture to Cloudinary (Optional)", max_length=255, null=True, verbose_name='image'),
        ),
    ]
