# Generated by Django 5.2.15 on 2026-07-11 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_patientprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='medical_history',
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('treatment_notes', models.TextField()),
                ('prescribed_medication', models.JSONField(blank=True, help_text="JSON format: {'meds': ['Napa', 'Seclo']}", null=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_histories', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
    ]
