# Generated by Django 5.2.15 on 2026-07-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_patientprofile_medical_history_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, help_text="Enter patient's full address", null=True),
        ),
    ]
