# Generated by Django 5.2.15 on 2026-06-08 17:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine Categories',
            },
        ),
        migrations.CreateModel(
            name='MedicineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name of the medicine (e.g., Napa Extend)', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('strength', models.CharField(help_text='e.g., 500mg, 20mg, 10ml', max_length=50)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Buying price from manufacturer', max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maximum Retail Price (MRP)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sku_code', models.CharField(blank=True, help_text='Stock Keeping Unit / Barcode token', max_length=100, unique=True)),
                ('requires_prescription', models.BooleanField(default=False, help_text="True if it's a prescription-only drug (Schedule H)")),
                ('description', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='products.medicinecategory')),
                ('generic_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='products.genericname')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='products.manufacturer')),
            ],
        ),
    ]
