# Generated by Django 5.2.15 on 2026-06-09 04:26

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineproduct',
            name='image',
        ),
        migrations.CreateModel(
            name='MedicineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_primary', models.BooleanField(default=False, help_text='Check if this is the main image for the product.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.medicineproduct')),
            ],
        ),
    ]
