# Generated by Django 5.2.15 on 2026-06-09 06:39

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_medicineproduct_image_medicineimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineproduct',
            name='administration',
            field=models.TextField(blank=True, help_text='e.g., Consume as directed, preferably before meals.', null=True),
        ),
        migrations.AddField(
            model_name='medicineproduct',
            name='dosage_instructions',
            field=models.TextField(blank=True, help_text='e.g., Take 2-4 teaspoons (10-20 ml) 2-3 times daily.', null=True),
        ),
        migrations.AddField(
            model_name='medicineproduct',
            name='indications',
            field=models.TextField(blank=True, help_text='What diseases/conditions this works for', null=True),
        ),
        migrations.AddField(
            model_name='medicineproduct',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Medicinal herbs or chemical formulas included (e.g., Jatrik, Nutmeg, Ashwagandha)', null=True),
        ),
        migrations.AlterField(
            model_name='medicineproduct',
            name='description',
            field=models.TextField(blank=True, help_text='General description/overview of the medicine (e.g., Renix Ginseng Syrup is an effective general tonic...)', null=True),
        ),
        migrations.AlterField(
            model_name='medicineproduct',
            name='name',
            field=models.CharField(help_text='Brand name of the medicine (e.g., Renix Ginseng Syrup)', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicineproduct',
            name='side_effects',
            field=models.TextField(blank=True, help_text='Side effects details (e.g., No significant side effects have been observed.)', null=True),
        ),
        migrations.AlterField(
            model_name='medicineproduct',
            name='strength',
            field=models.CharField(help_text='e.g., 500mg, 20mg, 100ml, 200ml', max_length=50),
        ),
        migrations.CreateModel(
            name='MedicineFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='e.g., What are the benefits of taking ginseng syrup?', max_length=500)),
                ('answer', models.TextField(help_text='Answer to the corresponding question')),
                ('order', models.PositiveIntegerField(default=0, help_text='Used to arrange the sequence of questions')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.medicineproduct')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicineReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reviewer Name (e.g., Saruar)', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Optional Phone Field', max_length=20, null=True)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 Stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='Review text (e.g., 100% effective product.)')),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, help_text='Optional File chosen input', max_length=255, null=True, verbose_name='review_attachment')),
                ('is_approved', models.BooleanField(default=True, help_text='Toggle to hide/show reviews if moderation needed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.medicineproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
